boongObbang-plz/boongObbang

backend/src/main/java/com/example/boongObbang/config/SecurityConfig.java, backend/src/main/java/com/example/boongObbang/jwt/JwtAuthorizationFilter.java, backend/src/main/java/com/example/boongObbang/jwt/JwtProvider.java, backend/src/main/java/com/example/boongObbang/oauth2/OAuth2SuccessHandler.java
- "/", "/main/**", "/login/**", "/login" 이외에는 무조건 token을 검사하도록 구현했습니다
- 토큰잉 유효하지 않은 경우, 토큰이 만료된 경우에는 오류 메시지를 반환합니다
=> feat: JwtAuthorizationFilter 적용

docker-compose.yml, frontend/.gitignore, frontend/Dockerfile
feat: DefaultPage 건 merge 후 docker 관련 파일이 삭제되버려서 복구 + 클러스터 아이맥 사용 시의 구문 추가하였습니다.
=> fix: 삭제된 docker file 복구

backend/build.gradle, backend/src/main/java/com/example/boongObbang/controller/SettingController.java, backend/src/main/java/com/example/boongObbang/dto/CreateSettingRequestDto.java, backend/src/main/java/com/example/boongObbang/entity/Setting.java, backend/src/main/java/com/example/boongObbang/entity/User.java, backend/src/main/java/com/example/boongObbang/exception/CustomExceptionHandler.java, backend/src/main/java/com/example/boongObbang/exception/exceptions/NoExistEmailException.java, backend/src/main/java/com/example/boongObbang/repository/SettingRepository.java, backend/src/main/java/com/example/boongObbang/response/ResponseMessage.java, backend/src/main/java/com/example/boongObbang/service/SettingService.java, backend/src/test/java/com/example/boongObbang/controller/SettingControllerTest.java, backend/src/test/java/com/example/boongObbang/repository/SettingRepositoryTest.java, backend/src/test/java/com/example/boongObbang/service/SettingServiceTest.java
- 마차를 새롭게 생성하는 api를 구현하였습니다
- 테스트코드 모두 작성 완료했습니다
- 하지만 oauth2 로직을 잘못 작성하여, controller에 대한 테스트, postman으로 하는 테스트는 진행하지 못한 상태입니다
=> feat: 마차 생성하기 구현

backend/src/main/java/com/example/boongObbang/config/SecurityConfig.java, backend/src/main/java/com/example/boongObbang/controller/UserController.java, backend/src/main/java/com/example/boongObbang/dto/CreateSettingRequestDto.java, backend/src/main/java/com/example/boongObbang/jwt/JwtAuthorizationFilter.java, backend/src/test/java/com/example/boongObbang/controller/SettingControllerTest.java
- Controller Test시에 403에러가 나는 현상 발생
- 토큰 검증이 필요한 uri를 security config에서 `.anyRequest().authenticated());` 해두었기에 오류 발생하여, 이를 제거함
=> fix: controller 테스트시 403이 뜨는 오류 해결

backend/src/main/java/com/example/boongObbang/controller/SettingController.java, backend/src/main/java/com/example/boongObbang/dto/PatchSettingRequestDto.java, backend/src/main/java/com/example/boongObbang/exception/CustomExceptionHandler.java, backend/src/main/java/com/example/boongObbang/exception/exceptions/NoExistSettingException.java, backend/src/main/java/com/example/boongObbang/response/ResponseMessage.java, backend/src/main/java/com/example/boongObbang/service/SettingService.java, backend/src/test/java/com/example/boongObbang/controller/SettingControllerTest.java, backend/src/test/java/com/example/boongObbang/service/SettingServiceTest.java
- 마차 수정하기 구현했습니다
- body에 name, color, light 중 수정하기 원하는 값만 넣어주면 db에 수정하여 저장하는 로직입니다
=> feat: 마차 수정하기 구현

backend/src/main/java/com/example/boongObbang/controller/SettingController.java, backend/src/main/java/com/example/boongObbang/service/SettingService.java, backend/src/test/java/com/example/boongObbang/controller/SettingControllerTest.java, backend/src/test/java/com/example/boongObbang/service/SettingServiceTest.java
- 마차 삭제하기를 구현했습니다
- 마차를 삭제할때, 마차만 삭제하는 것이 아니라 회원탈퇴까지 한번에 이루어지는 로직입니다
=> feat: 마차 삭제하기 구현

backend/src/main/java/com/example/boongObbang/config/SecurityConfig.java, backend/src/main/java/com/example/boongObbang/controller/SettingController.java, backend/src/main/java/com/example/boongObbang/jwt/JwtProvider.java, backend/src/main/java/com/example/boongObbang/service/SettingService.java
- 로그아웃을 구현했습니다
- 로그인 시 redis에 저장된 토큰을 삭제하는 방식으로 로그아웃을 구현했습니다
- commit 중에 email 대신 email을 입력한 오류 해결은 변수 email이 아니라 문자열 email을 입력해버렸는데, commit 메시지에서는 티가 안나네요!
=> feat: logout 구현

backend/src/main/java/com/example/boongObbang/config/SecurityConfig.java, backend/src/main/java/com/example/boongObbang/controller/MainPageController.java, backend/src/main/java/com/example/boongObbang/dto/MainPageResponseDto.java, backend/src/main/java/com/example/boongObbang/dto/MessageDto.java, backend/src/main/java/com/example/boongObbang/entity/Message.java, backend/src/main/java/com/example/boongObbang/repository/MessageRepository.java, backend/src/main/java/com/example/boongObbang/service/MainPageService.java, backend/src/test/java/com/example/boongObbang/controller/MainPageControllerTest.java, backend/src/test/java/com/example/boongObbang/repository/MessageRepositoryTest.java, backend/src/test/java/com/example/boongObbang/service/MainPageServiceTest.java
=> feat: 나의 메인페이지 조회 구현

backend/src/main/java/com/example/boongObbang/controller/MainPageController.java, backend/src/main/java/com/example/boongObbang/dto/LinkResponseDto.java, backend/src/main/java/com/example/boongObbang/service/MainPageService.java, backend/src/test/java/com/example/boongObbang/controller/MainPageControllerTest.java, backend/src/test/java/com/example/boongObbang/service/MainPageServiceTest.java
- 나의 페이지에 편지를 쓸 수 있는 공유 링크를 제공하는 기능을 구현했습니다
- 현재는 url을 `http:localhost:8080`으로 설정했지만, 추후에 실 서비스시 사용할 도메인으로 변경할 예정입니다
=> feat: 링크 공유하기 구현

frontend/package-lock.json, frontend/package.json, frontend/src/components/NotMyMainPage/Bottom.jsx, frontend/src/components/NotMyMainPage/MakeLetterBTN.jsx
12월 25일이후부터 편지 작성 할 수 없도록 제어 적용하였습니다.
=> feat: 12월 25일이후 편지작성 제어 적용

backend/src/main/java/com/example/boongObbang/controller/MainPageController.java, backend/src/main/java/com/example/boongObbang/controller/UserController.java, backend/src/main/java/com/example/boongObbang/dto/MessageDto.java, backend/src/main/java/com/example/boongObbang/dto/ReadMessageResponseDto.java, backend/src/main/java/com/example/boongObbang/entity/Message.java, backend/src/main/java/com/example/boongObbang/service/MainPageService.java, backend/src/test/java/com/example/boongObbang/controller/MainPageControllerTest.java, backend/src/test/java/com/example/boongObbang/service/MainPageServiceTest.java
- 편지 읽기만 단독으로 구현하려 했으나, 편지 읽기 구현을 진행하던 도중 편지 쓰기 기능이 필요하다는 것을 깨닫고 불가피하게 2개 기능을 하나의 이슈와 pr로 구성하였습니다
- 편지 읽기는 idx를 통해 편지를 읽을 수 있습니다
- 단, 삭제된 편지이거나 편지의 주인이 본인이 아닌 경우 에러가 발생합니다
- 편지 삭제는 편지를 삭제하는 기능입니다
- 편지 삭제를 구현하며, 엔티티에 삭제되었는지 확인하는 새로운 컬럼을 생성하였기에, 새로운 컬럼을 반영하는 코드 수정이 있었습니다
=> feat: 편지 읽기, 편지 삭제 구현

backend/src/main/java/com/example/boongObbang/config/SecurityConfig.java, backend/src/main/java/com/example/boongObbang/controller/OtherMainPageController.java, backend/src/main/java/com/example/boongObbang/exception/CustomExceptionHandler.java, backend/src/main/java/com/example/boongObbang/exception/exceptions/UrlErrorException.java, backend/src/main/java/com/example/boongObbang/jwt/JwtAuthorizationFilter.java, backend/src/main/java/com/example/boongObbang/response/ResponseMessage.java, backend/src/main/java/com/example/boongObbang/service/MainPageService.java, backend/src/test/java/com/example/boongObbang/controller/MainPageControllerTest.java, backend/src/test/java/com/example/boongObbang/service/MainPageServiceTest.java
- 남의 페이지 조회를 구현했습니다
- 남의 메인페이지는 토큰 없이 접근이 가능하기에, JwtAuthorizationFilter를 타지 않도록 수정했습니다
=> feat: 남의 페이지 조회 구현

.github/workflows/main.yml
- git action을 도입하기 위한 yml파일을 생성했습니다
=> chore: git action yml파일 추가

.github/workflows/main.yml
- git action 실행 시에 cd backend/src/main/resources에서 오류가 난 상황
- 해당 폴더가 없어서 생긴 오류로 판단 후 폴더 생성
=> chore: git action yml파일에서 spring main/resources 폴더 추가

.github/workflows/main.yml
- docker env를 생성 시에 잘못된 문법을 사용하여 이를 수정했습니다
=> chore: git action yml파일에서 잘못된 문법 수정

.github/workflows/main.yml
- gitaction을 통해 docker 이미지를 업로드하고 ec2에서 다운 받은 후 실행하도록 구현했습니다
=> chore: git action yml 파일에서 ec2에 도커 이미지 pull 구현

.github/workflows/main.yml
- `a step cannot have both the uses and run keys` 라는 오류가 발생하여 run 문법을 script로 변경
=> chore: git action yml 파일에서 run을 script로 변경

.github/workflows/main.yml
- script 문법의 위치가 잘못되어서 수정하였습니다
=> chore: git action yml 파일에서 script 위치 변경

.github/workflows/main.yml
- docker build 시 .을 추가 하지 않아서, 추가했습니다
=> chore: git action yml 파일에서 docker build 문법오류 수정

.github/workflows/main.yml
- docker를 사용한 부분을 docker-compose로 변경하였습니다
=> chore: git action yml 파일에서 docker를 docker-compose로 변경

.github/workflows/main.yml
- ec2에 접속을 못하는 상황이 발생하여 ssh의 uses를 변경하여 이를 시도하는 작업입니다
=> chore: git action yml 파일에서 ssh uses 변경

.github/workflows/main.yml
- ssh 연결이 안되는 현상을 해결하기 위해 ssh 버전을 변경했습니다
=> chore: git action yml 파일에서 ssh 버전 변경

.github/workflows/main.yml
- ec2에서 docker 실행 전 clear하는 과정을 스크립트로 실행하도록 수정했습니다
=> chore: git action yml 파일에서 docker 이미지와 컨테이너 삭제 스크립트 실행문 추가

.github/workflows/main.yml, docker-compose.yml
- docker hub에 docker image들이 push 되지 않는 현상을 수정했습니다
=> chore: docker hub에 docker-compose push 오류 해결

.github/workflows/main.yml, docker-compose.yml
- 깃 액션 적용 도중 backend 코드가 제대로 진행되지 않는 상황이 발생하여, 잠시 주석 처리했습니다
=> chore: backend 테스트 시 오류 발생하여, 잠시 주석 처리

.github/workflows/main.yml
- docker hub를 사용한 배포에 문제가 있다고 판단되어 S3를 통한 배포를 적용하려고 합니다
- 그 중에서 코드 파일을 AWS S3으로 옮기는 명령문을 작성했습니다
=> chore: main에 push될 시 AWS S3로 파일 옮기는 github action yml파일 작성

.github/workflows/main.yml
- 사용하지 않는 docker hub 관련 명령어를 삭제했습니다
- AWS S3로 이동하는 명령어를 수정했습니다
=> chore: github action에서 AWS S3로 이동 명령어 수정

.github/workflows/main.yml
=> chore: AWS S3에 업로드 명령어 수정

.github/workflows/main.yml
- S3에 업로드 시 zip 파일로 업로드하도록 수정했습니다
- S3에 있는 zip파일을 codedeploy로 배포되도록 구현했습니다
=> chore: S3에 zip 형식으로 업로드 수정 및 codedeploy 추가

.github/workflows/main.yml
- S3에 zip 형식으로 업로드 시 경로문제를 해결하였습니다
=> chore: S3에 zip 형식으로 업로드 경로 문제 수정

.github/workflows/main.yml
- S3에 zip 형식으로 업로드시 경로 에러가 나서 이를 수정했습니다
=> chore: S3에 zip 형식으로 업로드 경로 에러 수정

.github/workflows/main.yml
=> chore: S3에 zip 형식으로 업로드 형식 수정

.github/workflows/main.yml
- S3에 업로드 시 `--delete` 옵션을 제거하였습니다
=> chore: S3에 업로드 시 옵션 제거

.github/workflows/main.yml
- Code Deploy 실행 시 경로 오류가 있어 이를 수정했습니다
=> chore: code deploy 실행 시 경로 수정

.github/workflows/main.yml
- env에 AWS Default Region을 추가했습니다
=> chore: aws default region 추가

.github/workflows/main.yml
- ubuntu의 버전을 최신 버전에서 18.04로 변경했습니다
=> chore:ubuntu 버전 변경

.github/workflows/main.yml
- 이전에 변경한 ubuntu-18.04를 사용하면 github action이 실행되지 않는 현상이 발견되어, code deploy 명령어에서 region을 추가했습니다
=> chore: code deploy 명령어 실행시 region 추가

.github/workflows/main.yml
- S3의 env에서 region 설정 부분을 수정하였습니다
=> chore: env region 다시 설정

.github/workflows/main.yml
- configure aws credentials를 추가 했습니다
=> chore: configure aws credentials 추가

appspec.yml, script/deploy.sh
- code deploy에서 사용할 appsepc.yml과 deploy.sh를 생성했습니다
=> chore: code deploy에서 사용할 appspec.yml과 deploy.sh 생성

appspec.yml
- appsepc.yml의 owner와 group을 수정하였습니다
=> chore: appspec.yml의 owner와 group 수정

.github/workflows/main.yml, script/deploy.sh
- main.yml에서 시크릿키를 사용시 $를 안넣은 오타를 수정했습니다
- deploy.sh에서 실행할 파일의 경로를 수정했습니다
=> chore: 오타 수정 및 경로 재설정

backend/src/main/java/com/example/boongObbang/controller/OtherMainPageController.java, backend/src/main/java/com/example/boongObbang/dto/WriteMessageResponseDto.java, backend/src/main/java/com/example/boongObbang/service/MainPageService.java, backend/src/test/java/com/example/boongObbang/controller/MainPageControllerTest.java, backend/src/test/java/com/example/boongObbang/service/MainPageServiceTest.java
- 남의 메인페이지에서 편지 쓰기를 구현했습니다
- 편지 쓰기 중복 방지를 위해 편지 쓰기를 완료하면 303 code와 함께 남의 메인페이지 조회 화면으로 리다이렉트 됩니다
=> feat: 편지 쓰기 구현

frontend/src/components/LoginPage/KakaoRedirect.jsx, frontend/src/components/MainPage/DefaultScreen.jsx, frontend/src/components/MainPage/ShareButton.jsx, frontend/src/components/SettingPage/DefaultScreen.jsx, frontend/src/components/SettingPage/FinalCheckDeleteId.jsx, frontend/src/components/SettingPage/FinalCheckLogout.jsx, frontend/src/components/SettingPage/StartButton.jsx, frontend/src/main.jsx, frontend/src/states/ModalState.js
포스트맨 기준 다음 내용이 추가되었습니다.
* 로그인 - 카카오 로그인
* 나의 메인페이지 - 메인 페이지 조회, 공유하기
* 설정 - 마차 만들기, 마차 수정하기, 로그아웃, 마차 삭제
+설정 페이지에서 메인페이지 조회 후 값 받아오기
=> feat: api 추가

frontend/src/components/MainPage/Light.jsx, frontend/src/components/MainPage/readLetter/CloseButton.jsx, frontend/src/components/MainPage/readLetter/DeleteButton.jsx, frontend/src/components/MainPage/readLetter/LetterPop.jsx, frontend/src/components/MainPage/readLetter/LetterPopLabel.jsx, frontend/src/components/MainPage/readLetter/LetterPopTextArea.jsx, frontend/src/components/NotMyMainPage/MakeLetter/TopOfChooseBOB.jsx, frontend/src/components/NotMyMainPage/MakeLetter/TopOfWriteLetter.jsx, frontend/src/components/NotMyMainPage/MakeLetter/WriteLetter.jsx, frontend/src/components/SettingPage/FinalCheckDeleteId.jsx, frontend/src/components/SettingPage/FinalCheckLogout.jsx, frontend/src/components/layout.jsx, frontend/src/pages/NotMyMainPage.jsx
편지 작성/편지 읽기, 최종확인 모달 스타일을 동일하게 맞추었고,
최대 사이즈 이후 조명 높이를 조정하였습니다.
=> fix: 모달 스타일 맞춤 & 반응형 조정

backend/src/main/java/com/example/boongObbang/config/SecurityConfig.java, backend/src/main/java/com/example/boongObbang/controller/UserController.java, backend/src/main/java/com/example/boongObbang/jwt/JwtAuthorizationFilter.java, backend/src/main/java/com/example/boongObbang/jwt/JwtProvider.java
- cors 오류를 해결하기 위해 cors filter를 적용하였습니다
=> fix: cors 오류 해결

frontend/Dockerfile, frontend/src/states/ModalState.js
메인페이지 새로고침 시, 보안을 위해 내부변수에 저장해둔 토큰 값이 초기화되어 API 에러가 발생합니다.
사용자 경험을 위해 로컬 스토리지에 저장되도록 recoil-persist 적용하였습니다.
=> fix: 새로고침 시 토큰 없어지는 문제 조치

frontend/src/components/MainPage/ShareButton.jsx, frontend/src/components/MainPage/readLetter/FinalCheckDelete.jsx, frontend/src/components/MainPage/readLetter/LetterPop.jsx, frontend/src/pages/MainPage.jsx, frontend/src/pages/NotMyMainPage.jsx
메인페이지 조회, 공유하기, 편지읽기, 편지삭제, 남의 메인페이지 조회 API 에 대한 에러 핸들링을 적용하였습니다.
=> fix: API 에러 핸들링 적용

backend/src/main/java/com/example/boongObbang/config/SecurityConfig.java, backend/src/main/java/com/example/boongObbang/dto/GoogleProfileDto.java, backend/src/main/java/com/example/boongObbang/dto/KakaoProfileDto.java, backend/src/main/java/com/example/boongObbang/jwt/JwtAuthorizationFilter.java, backend/src/main/java/com/example/boongObbang/jwt/JwtProvider.java, backend/src/main/java/com/example/boongObbang/service/MainPageService.java, backend/src/main/java/com/example/boongObbang/service/UserService.java, backend/src/test/java/com/example/boongObbang/controller/MainPageControllerTest.java, backend/src/test/java/com/example/boongObbang/controller/SettingControllerTest.java
- oauth를 프론트와 연결하면서 일어나는 오류들을 해결했습니다
=> fix: oauth 오류 수정 

backend/src/main/java/com/example/boongObbang/service/SettingService.java
- 회원 탈퇴 시 메세지 삭제를 하지 않아, 수정했습니다
=> fix: 회원 탈퇴 시 메세지 삭제 수정

backend/src/main/java/com/example/boongObbang/service/MainPageService.java, frontend/src/components/LoginPage/GoogleLoginButton.jsx, frontend/src/components/LoginPage/SocialKakao.jsx, frontend/src/components/MainPage/Light.jsx, frontend/src/components/MainPage/Roof.jsx
배포 버전을 아이폰에서 확인했을 때 지붕이 거의 안보이는 문제 조치를 위하여,
지붕 높이를 지정하고, 조명 위치를 약간 수정했습니다.
(로컬에서는 기존과 큰 차이는 없습니다.)
=> fix: 아이폰 지붕 잘림 문제 해결을 위한 지붕 높이 지정

frontend/src/components/LoginPage/Redirect.jsx, frontend/src/components/MainPage/DDay.jsx, frontend/src/components/MainPage/ShareButton.jsx, frontend/src/components/MainPage/readLetter/LetterPopLabel.jsx, frontend/src/components/MainPage/readLetter/LetterPopTextArea.jsx, frontend/src/components/NotMyMainPage/MakeLetter/WriteLetter.jsx, frontend/src/components/layout.jsx
배포 후 발견되어 서버에서 바로 수정했던 부분 깃헙에도 동기화 시켰습니다.
=> fix: 배포 후 발견된 프론트 에러 수정
